config/routes.rb
TodoAppRailsIphoneApi::Application.routes.draw do
  root to: 'static_pages#home'

  resources :lists do
    resources :todos
  end

  get '/signup', to: 'users#new'
  resources :users

  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete
  resources :sessions, only: :create
  match '/about', to: 'static_pages#about', via: :get

end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
  before_create :generate_access_token
  belongs_to :user

  private

  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
    end while self.class.exists?(access_token: access_token)
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :todos, dependent: :destroy
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  after_initialize :default_values

  belongs_to :list
  validates :item, presence: true

  private

  def default_values
    self.completed ||= false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :api_keys

  has_secure_password
  validate :password, presence: true
  validate :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def current_user?(user)
    user == current_user
  end

  def correct_user
    @user ||= User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def authorize
    case request.format
    when Mime::JSON, Mime::XML, Mime::ATOM
      authenticate_or_request_with_http_token do |token, options|
        user = User.find(params[:user_id])
        if user
          user.api_keys.exists?(access_token: token)
        end
      end
    else
      redirect_to signin_url, alert: 'Not authorized' if current_user.nil?
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authorize
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.paginate(page: params[:page], per_page: 10)

    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /lists/new
  def new
    @list = List.new

    respond_to do |format|
      format.html
      format.json {render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: 'new' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      user.api_keys.create!
      session[:user_id] = user.id
      redirect_to lists_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authorize
  before_action :set_list
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = @list.todos.paginate(page: params[:page], per_page: 5)
    respond_to do |format|
      format.html
      format.json { render json: @list }
    end
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /todos/new
  def new
    @todo = @list.todos.new

    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = @list.todos.build(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to [@list, @todo], notice: 'Todo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @list }
      else
        format.html { render action: 'new' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to [@list, @todo], notice: 'Todo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to list_todos_url(@list) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

  def set_list
    @list = List.find(params[:list_id])
  end
  def set_todo
      @todo = @list.todos.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:item, :completed_at)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: :show

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, notice: 'Signed up!'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      sha = Digest::SHA1.hexdigest(code)
      Rails.cache.fetch ['code', language, sha].join('-') do
        Pygments.highlight(code, lexer: language)
      end
    end
  end

  def markdown(text)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Todo-App-Rails-Iphone-Api" %></title>
<%= csrf_meta_tags %>

<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

<%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Markdown Todo", root_path, class: "brand" %>
      <div class="container nav-collapse">
        <ul class="nav">
          <li><%= link_to("Home", root_path) %></li>
          <li><%= link_to("About", "#") %></li>
          <li><%= link_to("Blog", "#") %></li>

          <% if current_user %>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", signout_path, method: :delete %>
              </li>
            </ul>
          </li>
          <% else %>
          <li> <%= link_to "Sign in", signin_path %></li>
          <li> <%= link_to "Sign up", signup_path %> </li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>

    <%= render 'layouts/header' %>

    <div class="container" style="margin-top: 50px;">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p class="text-center">&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                lists_path, :class => 'btn' %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lists/index.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= link_to list.id, list_path(list) %></td>
        <td><%= list.name %></td>
        <td><%=l list.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_list_path(list), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      list_path(list),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_list_path,
            :class => 'btn btn-primary' %>

app/views/lists/new.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lists/show.html.erb
<%- model_class = List -%>
<ul class="breadcrumb">
    <li>
      <%= link_to 'My Lists', lists_path() %>
      <span class="divider">/</span>
    </li>
    <li>
      <%= link_to 'Edit This List', list_todos_path(@list) %>
      <span class="divider">/</span>
    </li>
    <li class="active">
      <a href="#">Current List</a>
    </li>
</ul>

<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<% if @list.todos %>
  <h2>Todo items</h2>
  <%= render @list.todos %>
<% end %>

<h2>Add todo item</h2>
<%= render 'todos/form' %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<div class="hero-unit text-center">
  <h1>Welcome to Markdown Todo</h1>
  <p> Your Todo Items are awesome with Markdown!
  </p>
  <p>
    Use all the available syntax at <a alt="Markdown" href="http://daringfireball.net/projects/markdown"> Markdown project</a> to create your Todo items
  </p>
  <p>
    <%= link_to "Sign up now !", signup_path, class: 'btn btn-primary btn-large' %>
</div>

app/views/todos/_form.html.erb
<%= simple_form_for [@list, if @todo.nil? then @list.todos.build else @todo end], html: { class: 'form-horizontal' } do |f| %>

<%= f.input :item, input_html: {class: 'span6', rows: 3} %>
<%= f.input :completed %>

<div class="form-actions">
  <%= f.submit 'Save', class: 'btn btn-primary' %>
  <%= link_to t('.cancel', default: t("helpers.links.cancel")),
  list_todos_path(@list), class: 'btn' %>
</div>
<% end %>

app/views/todos/_todo.html.erb
<%- model_class = todo.class -%>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:item) %>:</strong></dt>
  <dd><%= markdown todo.item %></dd>
  <dt><strong><%= model_class.human_attribute_name(:completed) %></strong></dt>
  <dd><%= check_box_tag :completed, todo.completed.to_s, todo.completed, disabled: true %></dd>
</dl>

app/views/todos/edit.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render 'form' %>

app/views/todos/index.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1><%=t '.title', default:  model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:item) %></th>
      <th><%= model_class.human_attribute_name(:completed) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', default: t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= link_to todo.id, list_todo_path(@list, todo) %></td>
        <td><%= markdown todo.item %></td>
        <td><%= todo.completed %></td>
        <td><%=l todo.created_at %></td>
        <td>
          <%= link_to t('.edit', default: t("helpers.links.edit")),
                      edit_list_todo_path(@list, todo), class: 'btn btn-mini' %>
          <%= link_to t('.destroy', default: t("helpers.links.destroy")),
                      list_todo_path(@list, todo),
                      method: :delete,
                      data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
                      class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>
<%= link_to t('.new', default: t("helpers.links.new")),
            new_list_todo_path(@list), class: 'btn btn-primary' %>

app/views/todos/new.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1><%=t '.title', default:  [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render 'form' %>

app/views/todos/show.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:item) %>:</strong></dt>
  <dd><%= markdown @todo.item %></dd>
  <dt><strong><%= model_class.human_attribute_name(:completed) %>:</strong></dt>
  <dd><%= @todo.completed %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', default: t("helpers.links.back")),
              list_todos_path(@list), class: 'btn'  %>
  <%= link_to t('.edit', default: t("helpers.links.edit")),
              edit_list_todo_path(@list, @todo), class: 'btn' %>
  <%= link_to t('.destroy', default: t("helpers.links.destroy")),
              list_todo_path(@list, @todo),
              method: 'delete',
              data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
              class: 'btn btn-danger' %>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= simple_form_for(@user, html: { class: 'form-horizontal'}) do |f| %>
<%= f.input :email %>
<%= f.input :password %>
<%= f.input :password_confirmation %>
<div class="form-actions">
  <%= f.button :submit, class: 'btn-primary' %>
  <%= submit_tag 'Cancel', type: 'reset', class: 'btn btn-danger' %>
</div>
<% end %>

app/views/users/show.html.erb
<section class="row">
  <h1>Welcome: <%= @user.email %></h1>
  <p class="intro">Your current access_token: <%= @user.api_keys.first.access_token %></p>
  <p> Your user_id: <%= @user.id %> </p>
</section>